[app]
name = "glacier-toolchain"
key  = "this is your app key"

[app.http]
host = "127.0.0.1"
port = "8050"

[app.grpc]
host = "127.0.0.1"
port = "18050"


[glacierauth]
host = "127.0.0.1"
port = "18050"
client_id = "1"
client_secret = "dfdfdf"




[mongodb]
endpoints = ["127.0.0.1:27017"]
username = "1"
password = "1"
database = "f"

[log]
level = "debug"
path = "logs"
format = "text"
to = "stdout"